

name: Latest blog post workflow
on:
  schedule:
    # Runs every day at a certain time
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: InfraWay/post-medium-action@v1.1.1
        with:
          feed_list: "https://medium.com/feed/@adam-osman"
